language: "en"

pipeline:
- name: "nlp_spacy"
  model: "en_core_web_md"
  case_sensitive: false
- name: "tokenizer_spacy"
- name: "intent_featurizer_spacy"
- name: "intent_classifier_sklearn"
- name: "ner_spacy"
